### PR TITLE
Standalone PR from PavlinII

### PR DESCRIPTION
**Pull request by PavlinII**

### CODE REVIEW

**Review by pavel-mikula-sonarsource — COMMENTED** [review]
C

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
rqc

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
not yet

**Review by pavel-mikula-sonarsource — APPROVED** [review]
now

**Review by pavel-mikula-sonarsource — COMMENTED** [review]
C

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
x

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
x

**Review by pavel-mikula-sonarsource — DISMISSED** [review]
LGTM

**Review by andrei-epure-sonarsource — COMMENTED** [review]
test

**Review by andrei-epure-sonarsource — COMMENTED** [review]
test after dismissal of review

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]
request changes

**Review by andrei-epure-sonarsource — APPROVED** [review]
approve

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
rqc

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
still not happy

**Review by pavel-mikula-sonarsource — CHANGES_REQUESTED** [review]
rqc

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]
I am not satisfied ! Changes are needed!

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM

**Pull request closed without merging**
